### ISSUE TITLE
About implement of LaDI-VTON

### ISSUE THREAD

**Issue by kunqueen** [zengjianhao/CAT-DM#10]
Hi, your work is vey interesting and I admire your experiment very much. I would like to ask how you complete the experiments of LaDI-VTON on two NVIDIA GeForce RTX 4090 GPUs. When I do this, it comes to OutOfMemoryError. Many thanks.

**Comment by zengjianhao** [comment]
I've used the official checkpoints of LaDI-VTON to generate qualitative results, and a single RTX 4090 GPU was sufficient for this purpose. Training LaDI-VTON might requires more GPUs, but I haven't tried that myself.
