### ISSUE TITLE
Which facebookresearch_dinov2 is the code looking for?

### ISSUE THREAD

**Issue by Aukture** [zengjianhao/CAT-DM#13]
In CAT-DM\ldm\models\diffusion\control.py, I see below lines. They aren't correct. Which dinno files is the code looking  for?

```
self.dinov2_vits14 = torch.hub.load('/home/sd/.cache/torch/hub/facebookresearch_dinov2_main', 'dinov2_vitl14', source='local', pretrained=False)
state_dict = torch.load('/home/sd/Harddisk/zjh/Teacher/checkpoints/dinov2_vitl14_pretrain.pth')
```

**Comment by zengjianhao** [comment]
my fault, I will fix it

**Comment by Aukture** [comment]
I did push it to patch branch. But I don't know why have you set pretrained=False.

**Comment by zengjianhao** [comment]
My computer often cannot connect to the torch.hub, so I would like to load dino-v2 in local, but it does not matter.
