### ISSUE TITLE
What is "gan" in dataset loaded

### ISSUE THREAD

**Issue by Aukture** [zengjianhao/CAT-DM#14]
In test.py, I see  
`gan = batch["gan"].to(torch.float16).to(device)`

However, the dataset Loader, gives:
```
return {"GT": img,                  # [3, 512, 512]
                "inpaint_image": inpaint,   # [3, 512, 512]
                "inpaint_mask": mask,       # [1, 512, 512]
                "ref_imgs": refernce,       # [3, 224, 224]
                "hint": hint                # [5, 512, 512]
                }
```
What is the gan here?

**Comment by zengjianhao** [comment]
You can delete it, it is for pre-trained GAN-based model's results.

**Comment by zengjianhao** [comment]
This repository is for GC-DM, which does not need "gan".

**Comment by Aukture** [comment]
Hi @zengjianhao... test.py has a lot of dependancy on gan... Would it be possible to clean that up... or u may suggest on how it has to be done?

**Comment by zengjianhao** [comment]
I will finish it, but i am busy with thesis, TOEFL, and other things. Please wait a while....;

**Comment by Aukture** [comment]
Hi @zengjianhao .. i'm urgently in need for completing this... and your implementation was something i was looking for very long. can we have a quick connect please (promise to not take much time)..I'll help to cleanup the content too...

**Comment by ThanhCong19** [comment]
@Aukture test.py in your forked this repo, I saw you can get:
![image](https://github.com/user-attachments/assets/f1b006d2-5595-498d-8efb-44116a21d142)
Can I have you code! pls, thanks.
