### ISSUE TITLE
Where is the pbe model used?

### ISSUE THREAD

**Issue by Aukture** [zengjianhao/CAT-DM#15]
Where is the pbe model specific to dresscode, regular pbe and vton pbe used?

**Comment by zengjianhao** [comment]
pbe model specific to dresscode: pbe_dim5.ckpt
pbe model specific to vitonhd: pbe_dim6.ckpt
regular pbe: pbe.ckpt

**Comment by Aukture** [comment]
I don't see it being used in code... Can u help to clarify this please
