### ISSUE TITLE
When code?

### ISSUE THREAD

**Issue by Bilal143260** [zengjianhao/CAT-DM#3]

**Comment by zengjianhao** [comment]
After our paper is accepted, I'm not sure exactly when that is.

**Comment by zengjianhao** [comment]
> > After our paper is accepted, I'm not sure exactly when that is.
> 
> I see this on a lot of repos, who is it that is 'accepting papers' ?

I guess these repositories are for papers submitted to CVPR 2024. I'm not quite sure if it's policy-compliant to say so.
