### ISSUE TITLE
`gan = batch["gan"].to(torch.float16).to(device)`

### ISSUE THREAD

**Issue by hcl14** [zengjianhao/CAT-DM#7]
Hi, thanks very much for the model code and checkpoints! 

I have a problem with the following line in `test.py`:

```
gan = batch["gan"].to(torch.float16).to(device)
```

Dataloader does not seem to provide this data, though it is used in prediction. What should I do?

Thank you!

PS, In order to load generated checkpoint for VITON-HD dataset I needed to change this line

```
model.load_state_dict(torch.load(opt.ckpt, map_location="cpu"), strict=False)
```

**Comment by zengjianhao** [comment]
I am currently in the process of uploading my code, but I've noticed that it contains issues such as comments in Chinese, non-standard naming conventions, and redundant code. Therefore, I am undertaking a thorough refactoring and optimization of the code, which may take some time. 

Now, you can train this model in the VITON-HD dataset, I have updated and verified this part of the code. `test_vitonhd.sh`, `train_dresscode.sh` and `test_dresscode.sh` need more time.

**Comment by Aukture** [comment]
@hcl14 .. what changes did you make to handle gan ?
